language: objective-c
osx_image: xcode8.2

xcode_project: CollectionGraph.xcodeproj # path to your xcodeproj folder
xcode_scheme: CollectionGraph
xcode_sdk: iphonesimulator10.2

# script: xcodebuild test -project CollectionGraph.xcodeproj -scheme CollectionGraph -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'
script: xctool test -project CollectionGraph.xcodeproj -scheme CollectionGraph test -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'

notifications:
  #slack: collectiveidea:UAduo5riNzgVWHyExXgSnZWk
